PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?item ?itemLabel WHERE {
  ?item wdt:P31 wd:Q7840353 ;
        rdfs:label ?itemLabel .
  FILTER(LANG(?itemLabel) = "en")
}
