# Time Precision value list
# Static enumeration of Wikibase time precision codes (integer 0-14).
# Fermenter should cast selected item to integer for time.precision.

SELECT ?item ?itemLabel WHERE {
  VALUES (?item ?itemLabel) {
    ("0"  "Gigayear (10^9 years)"@en)
    ("1"  "100 Megayears (10^8 years)"@en)
    ("2"  "10 Megayears (10^7 years)"@en)
    ("3"  "Megayear (10^6 years)"@en)
    ("4"  "100 Kiloyears (10^5 years)"@en)
    ("5"  "10 Kiloyears (10^4 years)"@en)
    ("6"  "millennium"@en)
    ("7"  "century"@en)
    ("8"  "decade"@en)
    ("9"  "year"@en)
    ("10" "month"@en)
    ("11" "day"@en)
    ("12" "hour"@en)
    ("13" "minute"@en)
    ("14" "second"@en)
  }
}
