meta_wikibase:
  id: datadistillery-wikibase
  label: Data Distillery Wikibase
  api_url: https://datadistillery.wikibase.cloud/w/api.php
  sparql_endpoint: https://datadistillery.wikibase.cloud/query/sparql

  semantic_conventions:
    name_identifier_property_id: P214
    internal_name_identifier_prefix: "_"

  value_list_talk_pages:
    rules:
      - class_name_identifier: _sparql_value_list
        block_type: sparql
        artifact_store: value_list_queries
      - class_name_identifier: _embedded_value_list
        block_type: json
        artifact_store: value_list_cache

spiritsafe:
  layout_version: 2

  roots:
    materialized: still
    partners: partners

  paths:
    entities: still/entities
    profiles: still/profiles
    value_list_queries: still/value_lists/queries
    value_list_cache: still/value_lists/cache
    semantic_anchors: config/semantic_anchors.json
    logs: still/logs
    wikimedia_sites: partners/wikimedia_sites.json