PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?item ?itemLabel WHERE {
  {
    BIND("1" AS ?item)
    BIND("unitless"@en AS ?itemLabel)
  }
  UNION
  {
    VALUES ?class {
      wd:Q47574      # unit of measurement
    }
    ?item wdt:P31 ?class ;
          rdfs:label ?itemLabel .
    FILTER(LANG(?itemLabel) = "en")
  }
}
ORDER BY ?itemLabel
